version: '3.9'

services:
  postgres:
    image: 'postgres:16-alpine'
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_HOST: '${DB_HOST}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    ports:
      - '${DB_PORT}:${DB_PORT}'
    networks:
      - ankle-network
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'

  redis:
    image: 'redis:7.2.3'
    container_name: redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT}
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    networks:
      - ankle-network
    volumes:
      - 'redis-data:/data'

  ankle:
    container_name: ankle
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
    networks:
      - ankle-network
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local

networks:
  ankle-network:
    driver: bridge
